name: pointvs
channels:
  - anaconda
  - pyg
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.3.2
  - binutils_impl_linux-64=2.36.1
  - blas=1.0
  - boost=1.74.0
  - boost-cpp=1.74.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.9.14
  - cairo=1.16.0
  - certifi=2022.9.14
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.1.3
  - cryptography=37.0.1
  - cudatoolkit=11.3
  - curl=7.84.0
  - cycler=0.11.0
  - dbus=1.13.18
  - docker-pycreds=0.4.0
  - expat=2.4.8
  - fastparquet=0.8.3
  - ffmpeg=4.3
  - fftw=3.3.9
  - fontconfig=2.14.0
  - fonttools=4.25.0
  - freetype=2.11.0
  - gcc=12.1.0
  - gcc_impl_linux-64=12.1.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - gitdb=4.0.9
  - gitpython=3.1.27
  - glew=2.1.0
  - glib=2.72.1
  - glib-tools=2.72.1
  - glm=0.9.9.4
  - gmp=6.2.1
  - gnutls=3.6.15
  - greenlet=1.1.3
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - gxx=12.1.0
  - gxx_impl_linux-64=12.1.0
  - hdf4=4.2.15
  - hdf5=1.10.6
  - icu=68.2
  - idna=3.3
  - intel-openmp=2021.4.0
  - jpeg=9e
  - kernel-headers_linux-64=2.6.32
  - kiwisolver=1.4.2
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=11.1.0
  - libcurl=7.84.0
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-devel_linux-64=12.1.0
  - libgcc-ng=12.1.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libglib=2.72.1
  - libglu=9.0.0
  - libgomp=12.1.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libllvm10=10.0.1
  - libllvm11=11.1.0
  - libnetcdf=4.7.4
  - libnghttp2=1.46.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=13.5
  - libprotobuf=3.21.5
  - libsanitizer=12.1.0
  - libssh2=1.10.0
  - libstdcxx-devel_linux-64=12.1.0
  - libstdcxx-ng=12.1.0
  - libtasn1=4.16.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.15
  - libxkbcommon=1.0.3
  - libxml2=2.9.10
  - libzlib=1.2.12
  - llvm-openmp=14.0.4
  - lz4-c=1.9.3
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - mysql-common=8.0.30
  - mysql-libs=8.0.30
  - ncurses=6.3
  - nettle=3.7.3
  - nspr=4.33
  - nss=3.74
  - numexpr=2.8.3
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openbabel=3.1.1
  - openh264=2.1.1
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.4.3
  - pathtools=0.1.2
  - pcre=8.45
  - pillow=9.2.0
  - pip=22.1.2
  - pixman=0.40.0
  - plip=2.2.2
  - ply=3.11
  - pmw=2.0.1
  - promise=2.3
  - protobuf=4.21.5
  - psutil=5.9.2
  - pycairo=1.21.0
  - pycparser=2.21
  - pyg=2.0.4
  - pymol-open-source=2.5.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.12.3
  - pysocks=1.7.1
  - pytest=7.1.2
  - python=3.8.13
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=1.11.0
  - pytorch-mutex=1.0
  - pytz=2022.1
  - pyyaml=6.0
  - qt=5.12.9
  - rdkit=2022.03.5
  - readline=8.1.2
  - reportlab=3.5.68
  - requests=2.28.1
  - rich=12.6.0
  - scipy=1.7.3
  - sentry-sdk=1.9.8
  - setproctitle=1.3.2
  - shortuuid=1.0.9
  - sip=6.6.2
  - six=1.16.0
  - smmap=3.0.5
  - sqlalchemy=1.4.41
  - sqlite=3.39.2
  - sysroot_linux-64=2.12
  - tk=8.6.12
  - toml=0.10.2
  - torchaudio=0.11.0
  - torchvision=0.12.0
  - tornado=6.2
  - typing_extensions=4.3.0
  - urllib3=1.26.11
  - wandb=0.13.1
  - wheel=0.37.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - egnn-pytorch==0.2.6
    - "--editable=git+ssh://git@github.com/jscant/plip.git#egg=plip"