name: pointvs
channels:
  - pytorch
  - anaconda
  - schrodinger
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - alsa-lib=1.2.3=h516909a_0
  - apbs=1.5=h14c3975_3
  - argh=0.26.2=pyh9f0ad1d_1002
  - attrs=21.2.0=pyhd3eb1b0_0
  - biopython=1.79=py38h497a2fe_0
  - blas=1.0=mkl
  - boost=1.74.0=py38hc10631b_3
  - boost-cpp=1.74.0=h312852a_4
  - brotlipy=0.7.0=py38h497a2fe_1001
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.2=h7f98852_0
  - ca-certificates=2021.7.5=h06a4308_1
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=h6cf1ce9_1008
  - certifi=2021.5.30=py38h06a4308_0
  - cffi=1.14.6=py38ha65f79e_0
  - chardet=4.0.0=py38h578d9bd_1
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - click=8.0.1=py38h578d9bd_0
  - collada2gltf=2.1.4=h6bb024c_0
  - configparser=5.0.2=pyhd8ed1ab_0
  - cryptography=3.4.7=py38ha5dfef3_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - curl=7.78.0=hea6ffbf_0
  - cycler=0.10.0=py_2
  - dbus=1.13.6=h48d8840_2
  - docker-pycreds=0.4.0=py_0
  - expat=2.4.1=h9c3ff4c_0
  - fastparquet=0.7.1=py38h6c62de6_0
  - fontconfig=2.13.1=hba837de_1005
  - freetype=2.10.4=h0708190_1
  - gettext=0.19.8.1=h0b5b191_1005
  - gitdb=4.0.7=pyhd8ed1ab_0
  - gitpython=3.1.18=pyhd8ed1ab_0
  - glew=2.1.0=h9c3ff4c_2
  - glib=2.68.3=h9c3ff4c_0
  - glib-tools=2.68.3=h9c3ff4c_0
  - gql=0.1.0=py_0
  - graphql-core=3.1.5=pyhd8ed1ab_0
  - gst-plugins-base=1.18.4=hf529b03_2
  - gstreamer=1.18.4=h76c114f_2
  - h5py=3.3.0=nompi_py38h9915d05_100
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.10.6=nompi_h3c11f04_101
  - icu=68.1=h58526e2_0
  - idna=3.1=pyhd3deb0d_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - jbig=2.1=h7f98852_2003
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9d=h36c2ea0_0
  - kiwisolver=1.3.1=py38h1fd1430_1
  - krb5=1.19.2=hcc1bbae_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - lerc=2.2.1=h9c3ff4c_0
  - libclang=11.1.0=default_ha53f305_1
  - libcurl=7.78.0=h2574ce0_0
  - libdeflate=1.7=h7f98852_5
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=hcdb4288_3
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.1.0=hc902ee8_8
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglib=2.68.3=h3e27bee_0
  - libglu=9.0.0=he1b5a44_1001
  - libholoplaycore=0.1.0_rc4=1
  - libiconv=1.16=h516909a_0
  - libllvm11=11.1.0=hf817b99_2
  - libnetcdf=4.8.0=nompi_hcd642e3_103
  - libnghttp2=1.43.0=h812cca2_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.10=h5a2b251_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libpq=13.3=hd57d9b9_0
  - libprotobuf=3.17.2=h780b84a_1
  - libssh2=1.9.0=ha56f1ee_6
  - libstdcxx-ng=11.1.0=h56837e0_8
  - libtiff=4.3.0=hf544144_1
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.40.0=h7b6447c_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.2.0=h7f98852_2
  - libxcb=1.13=h7f98852_1003
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - libzip=1.8.0=h4de3113_0
  - llvm-openmp=12.0.1=h4bd325d_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - matplotlib-base=3.4.2=py38hcc49a3a_0
  - mengine=1=h14c3975_1
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.0=py38h42c9631_2
  - mkl_random=1.2.2=py38h51133e4_0
  - more-itertools=8.8.0=pyhd3eb1b0_0
  - mpeg_encode=1=h14c3975_1
  - mtz2ccp4_px=1.0=h9ac9557_3
  - mysql-common=8.0.25=ha770c72_2
  - mysql-libs=8.0.25=hfa10184_2
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.2=hff7bd54_1
  - nspr=4.30=h9c3ff4c_0
  - nss=3.69=hb5efdd6_0
  - numpy=1.20.3=py38hf144106_0
  - numpy-base=1.20.3=py38h74d4b33_0
  - nvidia-ml=7.352.0=py_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1k=h27cfd23_0
  - packaging=21.0=pyhd3eb1b0_0
  - pandas=1.3.1=py38h1abd341_0
  - pathtools=0.1.2=py_1
  - pcre=8.45=h9c3ff4c_0
  - pdb2pqr=2.1.2+pymol=py_0
  - pillow=8.3.1=py38h8e6f84c_0
  - pip=21.2.2=py38h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - pluggy=0.13.1=py38h06a4308_0
  - pmw=2.0.1+3=py_3
  - promise=2.3=py38h578d9bd_3
  - protobuf=3.17.2=py38h709712a_0
  - psutil=5.8.0=py38h497a2fe_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - py=1.10.0=pyhd3eb1b0_0
  - pycairo=1.20.1=py38hf61ee4a_0
  - pycollada=0.7.1+bdf414c7=py_1
  - pycparser=2.20=pyh9f0ad1d_2
  - pykerberos=1.2.1=py38hacac60f_5
  - pymol=2.5.1=py38hffc77be_0
  - pymol-bundle=2.5.1=0
  - pymol-web-examples=2.4=1
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py38h578d9bd_7
  - pyqt-impl=5.12.3=py38h7400c14_7
  - pyqt5-sip=4.19.18=py38h709712a_7
  - pyqtchart=5.12=py38h7400c14_7
  - pyqtwebengine=5.12.1=py38h7400c14_7
  - pysocks=1.7.1=py38h578d9bd_3
  - pytest=6.2.4=py38h06a4308_2
  - python=3.8.11=h12debd9_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch=1.9.0=py3.8_cuda10.2_cudnn7.6.5_0
  - pytz=2021.1=pyhd8ed1ab_0
  - pyyaml=5.3.1=py38h7b6447c_1
  - qt=5.12.9=hda022c4_4
  - rdkit=2021.03.4=py38hf8acc3d_0
  - readline=8.1=h27cfd23_0
  - reportlab=3.5.68=py38hadf75a6_0
  - requests=2.26.0=pyhd8ed1ab_0
  - rigimol=1.3=2
  - scikit-learn=0.24.2=py38ha9443f7_0
  - scipy=1.6.2=py38had2a1c9_1
  - sentry-sdk=1.3.1=pyhd8ed1ab_0
  - setuptools=52.0.0=py38h06a4308_0
  - shortuuid=1.0.1=py38h578d9bd_4
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - sqlalchemy=1.3.23=py38h497a2fe_0
  - sqlite=3.36.0=hc218d9a_0
  - subprocess32=3.5.4=py_1
  - threadpoolctl=2.2.0=pyhb85f177_0
  - tk=8.6.10=hbc83047_0
  - toml=0.10.2=pyhd3eb1b0_0
  - torchaudio=0.9.0=py38
  - torchvision=0.2.2=py_3
  - tornado=6.1=py38h497a2fe_1
  - typing_extensions=3.10.0.0=pyh06a4308_0
  - urllib3=1.26.6=pyhd8ed1ab_0
  - vtk-m=1.5.1=hf484d3e_1
  - wandb=0.11.2=pyhd8ed1ab_0
  - watchdog=0.10.4=py38h578d9bd_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.5.0=ha95c52a_0
  - pip:
      - einops==0.3.0
      - egnn-pytorch==0.2.6
      - "--editable=git+ssh://git@github.com/oxcsml/lie-transformer.git#egg=Equivariant_Attention"
      - "--editable=git+ssh://git@github.com/pharmai/plip.git#egg=plip"
